### ISSUE TITLE
IT stability test list

### ISSUE THREAD

**Issue by nerdalert** [redhat-et/bpfd#155]
- [x] Initial framework to be able to respawn bpfd in IT (test PR #142)
- [x] install prog, list, delete (test PR #142)
- [ ] unload and then reload the same program (depends on #147) 
- [ ] verify the installer installs and starts the bpfd systemd svc (workflow PR #154)
- [x] ensure we don't panic If bpfd fails to process one of the commands (depends on #148) 
- [x] install prog, kill and respawn bpfd, list verify rules are there and bfd starts, delete progs, kill and respawn bpfd (depends on PR #142 and #149).

**Comment by astoycos** [comment]
Mostly done, the rest is stale.
